<?php
namespace app\common\model;

use app\common\model\Base;

class Ad extends Base{

    private $_ad;
    private $_ad_category;
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_ad = $this;
        $this->_ad_category = model('ad_category');
        $this->_base = $this;
    }
    //根据key查找广告
    public function getAdByKey($key,$limit = 3){
        $category_where = ['key'=>$key];
        $ad_category = $this->_ad_category->getList($category_where);
        if(empty($ad_category)){
            return false;
        }
        $ad_where['cid'] = $ad_category[0]['id'];
        $ad_where['status'] = 1;
        $ad_order = ['weight'=>'desc','id'=>'asc'];
        $ads = $this->_ad->getList($ad_where,$ad_order,$limit);
        return $ads;
    }
    //修改广告
    public function edit($where,$key = []){
        return $this->_ad->save($where,$key);
    }
    //删除分类
    public function typeDel($where){
        return $this->_ad->where($where)->delete();
    }
    // 异步获取分类
    public function getJsonType($where){
        $types = $this->_ad->where($where)->select();
        $val = [];
        foreach ($types as $type){
            $val[] = [$type['id'],$type['types']];
        }
        return json_encode($val,JSON_UNESCAPED_UNICODE);
    }


}