<?php
namespace app\common\model;

use app\common\model\Base;
use think\Db;

class Address extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_base = $this;
    }
    //添加商品进入购物车
    public function edit($data){
        $where = [];
        if(!empty($data['id'])){
            $where['id'] = $data['id'];
        }
        $data['addtime'] = time();
        return $this->save($data,$where);
    }
}