<?php
namespace app\common\model;

use app\common\model\Base;
use think\Db;

class Address extends Base
{
    private $_address;
    protected $resultSetType = 'collection';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_address = $this;
        $this->_base = $this;
    }
    //添加商品进入购物车
    public function addAddress($map,$where=[]){
        if(empty($where)){
            return $this->_address->save($map);
        }
        dump($where);
        return $this->_address->save($map,$where);
    }
}