<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class Arder extends Basely
{
    private $_arder;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_arder = $this;
        $this->_base = $this;
    }
    // 获取休闲卡列表
    public function getArders($where = [], $order = [], $page = 20){
        $join = [
            [['ww_merchant'=>'m'], 'a.mid = m.id']
        ];
        $field = ['a.*','m.name','m.phone'];
        return $this->_arder
            ->alias('a')
            ->join($join)
            ->field($field)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
    //获取单个
    public function getArder(){
        if(!input('pid')){
            return false;
        }
        $act = input('act');
        $where = ['id'=>input('pid')];
        if($act != 'admin'){
            $where['is_show'] = '1';
        }
        $arder = $this->_arder->where($where)->find();
        if(!$arder){
            return false;
        }
        $arder['pics'] = explode(',',$arder['pics']);
        $arder['merchant'] = Db::table('ww_merchant')->where(['id'=>$arder['mid']])->find();
        
        return $arder;
    }
    // 获取条件
    public function getWhere(){
        $where = 'status = "1"';
        return $where ;
    }
}