<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/17
 * Time: 9:20
 */

namespace app\common\model;


use think\Db;

class Cart extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    // 添加购物车操作
    public function create_cart($data){
        // good_id uid
        $field = ['goods_id','goods_name','original_img','shop_price','market_price','goods_sn','shipping_area_ids freight'];
        $good = Db::name('goods')
            ->where('goods_id',$data['good_id'])
            ->field($field)
            ->find();
        $good['freight'] = get_cache('logistics')[$good['freight']]['price'];
        if( !empty($data['spec_group']) ){
            $spec_field = ['id spec_group', 'specs_name', 'shop_price', 'market_price','goods_sn' ];
            $spec_group = Db::name('spec_group')
                ->where('id',$data['spec_group'])
                ->field($spec_field)
                ->find();
            $good = array_merge($good,$spec_group);
        }
        $good['uid'] = $data['uid'];
        $good['sum'] = $data['sum'];
        $good['addtime'] = time();
        $result = $this->save($good);
        if($result){
            return $this->getLastInsID();
        }
        return false;
    }
}