<?php
namespace app\common\model;

use app\common\model\Base;

class Cart extends Base
{
    private $_cart;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_cart = $this;
        $this->_base = $this;
    }
    //添加商品进入购物车
    public function addCart($map){
        return $this->_cart->save($map);
    }
    //修改购物车
    public function modCart($data,$where){
        return $this->_cart->save($data,$where);

    }
    //获取购物车
    public function getCarts($where){
        $field = ['c.id','c.gid','g.tradename gname','g.unit','g.pic','c.sum','g.ingprice price','g.oriprice ordprice','g.ratio','g.storeid','g.mid','g.freightway','g.freight'];
        return $this->_cart
            ->alias('c')
            ->field($field)
            ->join(config('database.prefix').'goods g','g.id = c.gid')
            ->where($where)
            ->paginate(20);
    }
    // 获取购物车总价
    public function getSumPrice($where){
        return $this->_cart
            ->alias('c')
            ->join(config('database.prefix').'goods g','g.id = c.gid')
            ->where($where)->value("sum(g.ingprice * c.sum)");
    }
    // 根据订单号获取商品
    public function getOCart($where){
        $carts = $this->getCarts($where);
        $ocarts = [];
        foreach ($carts as $cart){
            $ocarts[$cart['oid']][] = $cart;
        }
        return $ocarts;
    }
}