<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/25
 * Time: 15:58
 */

namespace app\common\model;


class Category extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    // 编辑操作
    public function edit($data){
        $map = [
            'name' => $data['name'],
            'mobile_name' => $data['mobile_name'],
            'is_show' => $data['is_show'],
            'weight' => $data['weight'],
            'image' => !empty($data['image'])?$data['image']:'',
        ];
        $map['pid'] = !empty($data['pid_2']) ? $data['pid_2'] : $data['pid_1'];
        $where = [];
        if(!empty($data['id'])){
            $where = ['id'=>$data['id']];
        }else{
            $map['addtime'] = time();
        }
        return $this->save($map,$where);
    }
    // 获取分类
    public function getCategory($where=[],$order=[]){
        return $this->where($where)->order($order)->select();
    }
    // 分类列表视图
    public function category_view($categorys,$pid = 0,$layer = 1){
        $html = '';
        foreach ($categorys as $category){
            $date = date('Y-m-d H:i:s',$category['addtime']);
            if($pid != $category['pid']){
                continue;
            }
            $hide = '';
            if($layer != 1){
                $hide = 'hide';
            }
            $html .= "<tr data-layer='$layer' class='$hide parent_{$layer}_{$category['pid']}'>
                        <td><i class=\"fa fa-plus sign\" data-id='{$category['id']}'></i></td>
                        <td>
                            <a href=\"javascript:void(0)\" data-toggle=\"tooltip\" title=\"Edit User\" class=\"btn btn-effect-ripple btn-xs btn-success\">
                                <i class=\"fa fa-pencil\">
                                </i>
                            </a>
                        </td>
                        <td class='text-center'>{$category['id']}</td>
                        <td>{$category['name']}</td>
                        <td>{$category['mobile_name']}</td>
                        <td>{$category['is_show']}</td>
                        <td>{$category['weight']}</td>
                        <td>{$date}</td>
                    </tr>";
            $html .= $this->category_view($categorys,$category['id'],$layer+1);
        }
        return $html;
    }
}