<?php
namespace app\common\model;

use app\common\model\Base;

class Comment extends Base
{
    private $_comment ;

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_comment = $this;
        $this->_base = $this;
    }
    /*
     * 关联查询商户，评论内容
     * */
    public function getComments($condition=[],$order=['id'=>'desc']){
        $join = [
            ['merchant m','c.mid = m.id'],
            ['userinfo u','c.uid = u.id'],
        ];
        $field = ['c.*','m.name','m.phone','u.nickname'=>'uname','u.phone'=>'uphone'];
        return $this->_comment
            ->alias('c')
            ->join($join)
            ->field($field)
            ->where($condition)->order($order)->paginate(20);
    }
    // 评论
    public function getComment($condition=[],$order=['c.addtime'=>'desc']){
        $join = [
            ['merchant m','c.mid = m.id'],
            ['userinfo u','c.uid = u.id'],
        ];
        $field = ['c.*','u.nickname'=>'uname','u.phone'=>'uphone','avg(score) score','avg(guide) guide','avg(scheduling) scheduling','avg(star) star','count(*) count'];
        $comment = $this->_comment
            ->alias('c')
            ->join($join)
            ->field($field)
            ->where($condition)->order($order)->find();
        return $comment;
    }
}