<?php
namespace app\common\model;

use think\Model;

class Dest extends Model
{
    private $_dest;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_dest = $this;
    }
    /*
     * 获取所有分类
     * */
    public function getDestList()
    {
        return $this->_dest->select();
    }
    /*
     * 递归获取联级分类
     * */
    public function callDestList()
    {
        
    }



}