<?php
namespace app\common\model;

use app\common\model\Base;
use think\Db;
use think\Loader;
use think\Model;

class Drawing extends Base
{
    private $_drawing;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_drawing = $this;
        $this->_base = $this;
    }
    // 申请提款列表
    public function getDrawings($where=[], $order=[], $page=20){
        $join = [
            ['merchant m','m.id=d.mid'],
        ];
        $field = ['d.*','m.name','m.phone'];
        return $this->_drawing
            ->alias('d')
            ->join($join)
            ->field($field)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
}