<?php
namespace app\common\model;

use app\common\model\Base;

class Integralog extends Base
{
    private $_integra;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_integra = $this;
        $this->_base = $this;
    }
    // 获取积分日志
    public function getLog($where=[],$order=[],$page=20){
        $join = [
            ['orders o' , 'o.id = i.oid']
        ];
        $field = ['i.*','o.onumber'];
        return $this->_integra
            ->alias('i')
            ->field($field)
            ->join($join)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
}