<?php
namespace app\common\model;

use app\common\model\Basely;

class Line extends Basely
{
    private $_line ;

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_line = $this;
        $this->_base = $this;
    }

    //获取线路信息列表
    public function getLines($where=[],$order=[],$page=20)
    {
        $join = [
            [['ww_merchant'=> 'm'] , 'l.mid = m.id'],
        ];
        $field = ['l.*','m.name mname','m.phone'];
        return $this->_line
            ->alias('l')
            ->join($join)
            ->field($field)
            ->where($where)->order($order)->paginate($page);
    }
    public function getListId($desid){
        $query = "select id from ly_line where  CONCAT(',',desid,',') REGEXP '[^0-9]+[".$desid."][^0-9]+'";
        $lines = $this->_line->query($query);
        $ids = [];
        foreach ($lines as $line){
            $ids[] = $line['id'];
        }
        return $ids;
    }
    // 线路
    public function getDestLine($desids){
        $lines = [];
        foreach ($desids as $desid){
            $query = "select * from ly_line where  CONCAT(',',desid,',') REGEXP '[^0-9]+[".$desid."][^0-9]+'";
            $line = $this->_line->query($query);
            $lines = array_merge($lines,$line);
        }
        $ids = [];
        foreach ($lines as $line){
            $ids[] = $line['id'];
        }
        return $ids;
    }
    // 根据地名显示id
    public function getTextId($dest){
        $where = ['destination'=>['like','%'.$dest.'%']];
        return $this->_line->where($where)->column('id');
    }

}