<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/28
 * Time: 15:27
 */

namespace app\common\model;


class Logistics extends Base
{
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_base = $this;
    }
    public function setCache(){
        $name = lcfirst($this->name);
        $logistics = $this->select();
        $logis = [];
        foreach ($logistics as $logistic){
            $logis[$logistic['id']] = $logistic;
        }
        get_cache($name,$logis);
    }
    // 邮费模板
    public function edit($data){
        if(empty($data['name'])){
            $this->error = '请填写邮费模板';
            return false;
        }
        $result = $this->save($data);
        $this->setCache();
        return $result;
    }
    // 邮费模板列表
    public function listing(){
        $logistics = $this->paginate(20);
        $page = $logistics->render();
        $list = [
            'title' => '邮费模板列表',
            'logistics' => $logistics,
            'page' => $page,
        ];

        return $list;
    }
    // 编辑视图
    public function edit_view(){

    }
}