<?php
namespace app\common\model;

use app\common\model\Base;

class Malltypes extends Base
{
    private $_malltypes ;

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_malltypes = $this;
        $this->_base = $this;
    }
    //修改分类
    public function typeEdit($where,$key = null){
        return $this->_malltypes->save($where,$key);
    }
    //删除分类
    public function typeDel($where){
        return $this->_malltypes->where($where)->delete();
    }
    // 异步获取分类
    public function getJsonType($where){
        $types = $this->_malltypes->where($where)->select();
        $val = [];
        foreach ($types as $type){
            $val[] = [$type['id'],$type['types']];
        }
        return json_encode($val,JSON_UNESCAPED_UNICODE);
    }



}