<?php
namespace app\common\model;

use app\common\model\Base;
use think\Db;

class Message extends Base
{

    private $_message;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_message = $this;
        $this->_base = $this;
    }
    // 获取消息联系人列表
    public function getMessageList($where = [],$group='',$having = [],$order=['addtime'=>'desc'],$page=20){
        $field = ['mid','sum(status) status_num', 'uid','message','addtime'];
        $build1 = $this->_message->where($where)->order($order)->buildSql();
        $build2 = Db::table($build1 . ' a')
            ->field($field)
            ->order($order)
            ->group($group)
            ->having($having)
            ->buildSql();
//        if($group == 'mid'){
//            $table = 'merchant';
//            $join = [
//                [$build2.' b', 'b.mid = c.id']
//            ];
//            $fields = ['b.mid','b.uid', 'b.status_num','b.message','b.addtime','c.logo','c.name'];
//        }elseif($group == 'uid'){
//            $table = 'userinfo';
//            $join = [
//                [$build2.' b', 'b.uid = c.id']
//            ];
//            $fields = ['b.mid','b.uid', 'b.status_num','b.message','b.addtime','c.headimg','c.nickname'];
//
//        }else{
//            $table = '';
//        }
        $join = [
            ['merchant m', 'm.id = b.mid'],
            ['userinfo u', 'u.id = b.uid']
        ];
        $fields =['b.mid','b.uid', 'b.status_num','b.message','b.addtime','u.headimg','u.nickname','m.logo','m.name'];
        return Db::table($build2.' b')->join($join)->field($fields)->paginate($page);
    }
    // 获取消息列表
    public function getMessages($where=[],$order=[],$page = 20){
        return $this->_message
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
    //修改消息的阅读状态
    public function message_status($where=[]){
        $map = ['status'=>0];
        return $this->_message->where($where)->update($map);
    }
}