<?php
namespace app\common\model;

use app\common\model\Base;

class Nav extends Base{

    private $_nav;
    private $_nav_category;
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_nav = $this;
        $this->_nav_category = model('nav_category');
        $this->_base = $this;
    }
    //根据key查找广告
    public function getNavByKey($key,$limit = 3){
        $category_where = ['key'=>$key];
        $nav_category = $this->_nav_category->getList($category_where);
        if(empty($nav_category)){
            return false;
        }
        $nav_where['cid'] = $nav_category[0]['id'];
        $nav_where['status'] = 1;
        $nav_order = ['weight'=>'desc','id'=>'asc'];
        $navs = $this->_nav->getList($nav_where,$nav_order,$limit);
        return $navs;
    }
    //修改导航
    public function edit($where,$key = []){
        return $this->_nav->save($where,$key);
    }
    //删除分类
    public function typeDel($where){
        return $this->_nav->where($where)->delete();
    }
    // 异步获取分类
    public function getJsonType($where){
        $types = $this->_nav->where($where)->select();
        $val = [];
        foreach ($types as $type){
            $val[] = [$type['id'],$type['types']];
        }
        return json_encode($val,JSON_UNESCAPED_UNICODE);
    }


}