<?php
namespace app\common\model;

use app\common\model\Base;

class NavCategory extends Base{

    private $_navCategory;
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_navCategory = $this;
        $this->_base = $this;
    }

}