<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Db;

class Offer extends Basely
{
    private $_offer ;

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_offer = $this;
        $this->_base = $this;
    }

    //获取获取行程
    public function getTrips($where=[],$order=[])
    {
//        dump($this->_offer
//            ->where($where)->order($order)->buildSql());
        return $this->_offer
            ->where($where)->order($order)->column('tid');
    }
    // 添加报价
    public function addOffer($offer,$tid){
        $time = time();
        $this->_offer->where(['tid'=>$tid])->delete();
        foreach ($offer as $item =>$value){
            $map = [
                'dates' => strtotime($item),
                'tid' => $tid,
                'adult' => $value['adult']?$value['adult']:0,
                'children' => $value['children']?$value['children']:0,
                'stock' => $value['stock']?$value['stock']:0,
                'addtime' => $time
            ];
            Db::table('ly_offer')->insert($map);
        }
    }

}