<?php
namespace app\common\model;

use app\common\model\Base;
use think\Db;

class Op extends Base
{
    private $_op;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_op = $this;
        $this->_base = $this;
    }
    // 操作员列表
    public function getOps($where,$order){
        $ops = $this->_op->where($where)->select();
    }
}