<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Db;

class People extends Basely
{
    private $_people;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_people = $this;
        $this->_base = $this;
    }
    public function peoples($where=[]){
        $join = [
            ['passport pa', "pa.pid = p.id"]
        ];
        $peopels = $this->_people->where($where[0])->select();
        foreach ($peopels as $i => $peopel){
            $where[1]['pid'] = $peopel['id'];
            $passports = Db::table('ly_passport')->where($where[1])->select();
            $peopels[$i]['pass'] = $passports;
        }
        return $peopels;
    }
}