<?php
namespace app\common\model;

use app\common\model\Base;
use think\Db;

class Play extends Base
{
    private $_play;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_play = $this;
        $this->_base = $this;
    }
    // 获取账单列表
    public function getPlays($where=[],$order=[],$page=20){
        return $this->_play
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
    // 加载其他数据
    public function getPlayDatas($where=[],$order=[],$page=20){
        $plays = $this->_play->getPlays($where,$order,$page);
        foreach ($plays as $k => $play){
            if($play['mid']){
                $plays[$k]['merchant'] = Db::table('ww_merchant')->where('id',$play['mid'])->find();
            }
            if($play['oid']){
                $order = Db::table('ly_shop')->where('id',$play['oid'])->find();
                $order['title'] = Db::table('ly_trip')->where('id',$order['tid'])->value('title');
                $plays[$k]['order'] = $order;
            }
            if($play['uid']){
                $plays[$k]['user'] = Db::table('ww_userinfo')->where('id',$play['uid'])->find();
            }
        }
        return $plays;
    }
    // 添加用户余额账单
    public function addPlay($shop,$status){
        $price = 0;
        $explain = '';
        $type = 0;
        if($status == 3){
            $price = $shop['sumprice'];
            $explain = '拒绝订单退款收入：' . $price;
            $type = 3;
        }else{
            $price = -$shop['sumprice'];
            $explain = '购买行程消费：' . $price;
            $type = 2;
        }
        $map = [
            'uid'=> $shop['uid'],
            'mid'=> $shop['mid'],
            'oid' => $shop['id'],
            'remark' => '商户拒绝订单退款',
            'price' => $price,
            'status' => 2,
            'type' => $type,
            'explain' => $explain,
            'addtime' => time()
        ];
        $_play = model('play');
        $result = $_play->save($map);
        return $result;
    }
}