<?php
namespace app\common\model;

use app\common\model\Base;

class Store extends Base
{
    private $_store ;

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_store = $this;
        $this->_base = $this;
    }
    /*
     * 获取商户下所有门店的信息
     * */
    public function getStores($mid = 0){
        return $this->_store->where(['mid'=>$mid])->select();
    }
    /*
     * 添加门店
     * */
    public function storeAdd($mid){
        $error = ['code'=>'1'];
        $map = [
            'mid'       => $mid,
            'store'     => input('store')?input('store'):'',
            'phones'    => input('phones')?input('phones'):'',
            'wechat'    => input('wechat')?input('wechat'):'',
            'qq'        => input('qq')?input('qq'):'',
            'highlights'=> input('highlights')?input('highlights'):'',
            'desc'      => input('desc')?input('desc'):'',
            'jingwei'   => input('jingwei')?input('jingwei'):'',
            'province'  => input('province')?input('province'):'',
            'city'      => input('city')?input('city'):'',
            'county'    => input('county')?input('county'):'',
            'address'   => input('address')?input('address'):'',
            'traffic'   => input('traffic')?input('traffic'):'',
            'weight'    => input('weight')?input('weight'):'',
            'addtime'   => time(),
        ];
        $result = $this->_store->save($map);
        if($result){
            return $error;
        }
        $error = ['code'=>'0','info'=>'添加成功'];
        return $error;
    }
    /*
     * 修改门店
     * */
    public function storeMod($sid){
        $error = ['code'=>'1'];
        $map = [
            'store'     => input('store')?input('store'):'',
            'phones'    => input('phones')?input('phones'):'',
            'wechat'    => input('wechat')?input('wechat'):'',
            'qq'        => input('qq')?input('qq'):'',
            'highlights'=> input('highlights')?input('highlights'):'',
            'desc'      => input('desc')?input('desc'):'',
            'jingwei'   => input('jingwei')?input('jingwei'):'',
            'province'  => input('province')?input('province'):'',
            'city'      => input('city')?input('city'):'',
            'county'    => input('county')?input('county'):'',
            'address'   => input('address')?input('address'):'',
            'traffic'   => input('traffic')?input('traffic'):'',
            'weight'    => input('weight')?input('weight'):'',
        ];
        dump($sid);
        $result = $this->_store->save($map,['id'=>$sid]);
        if($result){
            return $error;
        }
        $error = ['code'=>'0','info'=>'修改失败'];
        return $error;
    }


}