<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class Strategy extends Basely
{
    private $_strategy;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_strategy = $this;
        $this->_base = $this;
    }
    //异步获取攻略列表
    public function getStrategys($where = [], $order = [], $page = 20){
        $join = [
            [['ww_merchant'=>'m'], 's.mid = m.id']
        ];
        $field = ['s.*','m.name','m.phone'];
        return $this->_strategy
            ->alias('s')
            ->join($join)
            ->field($field)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
    public function getStrategy(){
        if(!input('pid')){
            return false;
        }
        $act = input('act');
        $where = ['id'=>input('pid')];
        if($act != 'admin'){
            $where['is_show'] = '1';
        }
        $strategy = $this->_strategy->where($where)->find();
        if(!$strategy){
            return false;
        }
//        $strategy['pics'] = explode(',',$strategy['pics']);
        $strategy['merchant'] = Db::table('ww_merchant')->where(['id'=>$strategy['mid']])->find();
//        $strategy_type = json_decode($strategy['ticket_type'],true);
        return $strategy;
    }
    // 条件获取
    public function getWhere(){
        $where = ' is_show = "1"';

        return $where;
    }

}