<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class Ticket extends Basely
{
    private $_ticket;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_ticket = $this;
        $this->_base = $this;
    }
    //获取门票列表
    public function getTickets($where = [], $order = [], $page = 20){
        $join = [
            [['ww_merchant'=>'m'], 't.mid = m.id']
        ];
        $field = ['t.*','m.name','m.phone'];
        return $this->_ticket
            ->alias('t')
            ->join($join)
            ->field($field)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
    public function getTicket(){
        if(!input('pid')){
            return false;
        }
        $act = input('act');
        $where = ['id'=>input('pid')];
        if($act != 'admin'){
            $where['status'] = '2';
        }
        $ticket = $this->_ticket->where($where)->find();
        if(!$ticket){
            return false;
        }
        $ticket['pics'] = explode(',',$ticket['pics']);
        $ticket['merchant'] = Db::table('ww_merchant')->where(['id'=>$ticket['mid']])->find();
        $ticket_type = Db::table('ly_ticket_type')->where('tid',$ticket['id'])->select();
        $ticket['ticket_types'] = $ticket_type;
        return $ticket;
    }
    // 条件获取
    public function getWhere(){
        $where = 't.status = 2 ';

        return $where;
    }
}