<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class TicketOrder extends Basely
{
    private $_ticket_order;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_ticket_order = $this;
        $this->_base = $this;
    }
    public function getOrders($where=[],$order=[],$page=20){
        $join = [
            [['ww_merchant'=> 'm'] , 'o.mid = m.id'],
            [['ww_userinfo'=> 'u'] , 'o.uid = u.id'],
            [['ly_ticket'=> 't'] , 'o.ticket = t.id'],
        ];
        $field = ['o.*','m.name','m.phone','u.name uname','u.nickname','t.title'];

        return $this->_ticket_order
            ->alias('o')
            ->join($join)
            ->field($field)
            ->where($where)->order($order)->paginate($page);
    }
}