<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class Trip extends Basely
{
    private $_trip ;
    private $_dest ;
    private $_line ;
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_trip = $this;
        $this->_dest = model('destination');
        $this->_line = model('line');
        $this->_base = $this;
    }

    //获取线路信息列表
    public function getTrips($where=[],$order=[],$page=20)
    {
        $join = [
            [['ww_merchant'=> 'm'] , 't.mid = m.id'],
            [['ly_line'=> 'l'] , 't.lid = l.id'],
        ];
        $field = ['t.*','m.name','m.phone','l.destination','l.days'];
//        dump($this->_trip
//            ->alias('t')
//            ->join($join)
//            ->field($field)
//            ->where($where)->order($order)->buildSql());
        return $this->_trip
            ->alias('t')
            ->join($join)
            ->field($field)
            ->where($where)->order($order)
            ->paginate($page);
    }
    // 获取申请特价甩尾的行程
    public function getFlicks($where=[],$order=[],$page=20){
        $join = [
            [['ww_merchant'=> 'm'] , 't.mid = m.id'],
            [['ly_trip_flick'=> 'f'] , 'f.tid = t.id'],
        ];
        $field = ['t.*','m.name','m.phone','f.sale','f.desc f_desc','f.status f_status','f.second','f.modtime'];
        return $this->_trip
            ->alias('t')
            ->join($join)
            ->field($field)
            ->where($where)->order($order)
            ->paginate($page);
    }
    // 待审核信息行程
    public function trip_num($where=[]){
        $where = array_merge($where,['status'=>'1']);
        return $this->_trip->where($where)->count('id');
    }
    //获取行程
    public function getTrip(){
        if(!input('pid')){
            return false;
        }
        $act = input('act');
        $where = ['id'=>input('pid')];
        if($act != 'admin'){
            $where['status'] = '2';
        }
        $trip = $this->_trip->where($where)->find();
        if(!$trip){
            return false;
        }
        $s_where = ['id'=>['in',$trip['safe']]];
        $safes = Db::table('ly_safe')->where($s_where)->select();
        $trip['safes'] = $safes;
        $trip['pics'] = explode(',',$trip['pics']);
        $trip['merchant'] = Db::table('ww_merchant')->where(['id'=>$trip['mid']])->find();
        $trip['line'] = Db::table('ly_line')->where(['id'=>$trip['lid']])->find();
        $thread = json_decode($trip['line']['thread'],true);
        $trip['threads'] = $thread;
        $c_where = ['c.gid'=>$trip['id'],'c.type'=>'1'];
        $score = model('comment')->getComment($c_where);
        $score['good'] = model('comment')->where(['gid'=>$trip['id'],'type'=>'1','star'=>1])->count();
        $trip['score'] = $score;
        return $trip;
    }
    // 行程检索条件
    public function getWhere(){
        $keyword = input('keyword');
        $setout = input('setout');
        $start = input('start');
        $end = input('end');
        $min = input('min');
        $max = input('max');
        $day_min = input('day_min');
        $day_max = input('day_max');
        $pro_type = input('pro_type');
        $style = input('style');
        $poster = input('poster');
        $flick = $pro_type == 'flick'?'1':'0';
        $where = ' `t`.`situation` = 1 and `m`.`status` = 2 and `t`.`flick` = '.$flick.' and `t`.`after_date` >= '. date('Ymd');
        $timeTo = [];
        if($keyword){
            $where .= ' and (`t`.`title` like "%'.$keyword.'%" or `t`.`setout` like "%'.$keyword.'%" or `l`.`destination` like "%'.$keyword.'%" or `t`.`id` = "'.$keyword.'") ';
        }
        if($setout){
            $where .= ' and `t`.`setout` like "%'.substr($setout,0,6).'%"';
        }
        if($style){
            $where .= ' and `t`.`style` = ' . $style;
        }
        if($start){
            $timeTo['dates'][] = ['>=',strtotime($start)];
        }
        if($end){
            $timeTo['dates'][] = ['<=',strtotime($end)];
        }
        if($start || $end){
            $ids = model('offer')->getTrips($timeTo);
//                        dump($ids);
            $ids = array_unique($ids);
            if(!empty($ids)){
                $where .= ' and `t`.`id` in ('.implode(',',$ids).')';
            }
        }
        if($min){
            $where .= ' and `t`.`minprice` >= '.$min;
        }
        if($max){
            $where .= ' and `t`.`maxprice` <= '.$max;
        }
        if($day_min){
            $where .= " and `l`.`days` >=" . $day_min;
        }
        if($day_max){
            $where .= " and `l`.`days` <= " . $day_max;
        }
        if($poster == 1){
            $where .= ' and `t`.`poster` !=""';
        }
        if($pro_type){
            switch ($pro_type){
                case 'hot': //热门
                    $where .= " and `t`.`hot` = '1'";
                    break;
                case 'flick': //甩尾单
                    $where .= " and `t`.`flick` = '1'";
                    break;
                case 'periphery': //周边游
                    $dests = '1';
                    $where .= " and CONCAT(',',`l`.`desid`,',') REGEXP '[^0-9]+[".$dests."][^0-9]+'";
                    break;
                case 'domestic': // 国内游
                    $where .= ' and `t`.`type` = "1"';
                    break;
                case 'exit':    // 出境游
                    $where .= ' and `t`.`type` = "2"';
                    break;
                case 'island':  //海岛游
                    $where .= ' and `t`.`play` = "1"';
                    break;
                case 'cruise':  //游轮之旅
                    $where .= ' and `t`.`play` = "2"';
                    break;
                case 'parenting':  //游轮之旅
                    $where .= ' and `t`.`play` = "3"';
                    break;
                case 'weekend': // 周末游
                    $week = getWeekend();
                    $o_where = ['dates'=>['in',implode(',',$week)]];
                    $trips = model('offer')->getTrips($o_where);
                    $trips = array_unique($trips);

                    $where .= ' and `t`.`id` in ('.implode(',',$trips).') and `t`.`type` = "1"';
//                    $where['t.id'] = ['in',implode(',',$trips)];
                    break;
            }
        }
        $where .= ' and `t`.`status` = "2"';
        return $where;
    }



}