<?php
namespace app\common\model;

use app\common\model\Base;

class Types extends Base
{
    private $_types ;

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_types = $this;
        $this->_base = $this;
    }
    /*
     * 根据条件获取商品类型
     * */
    public function getTypes($where){
        return $this->_types->where($where)->select();
    }
    /*
     * 格式化商品类型的
     * */
    public function getJsonType($where){
        $types = $this->_types->getTypes($where);
        $val = [];
        foreach ($types as $type){
            $val[] = [$type['id'],$type['types']];
        }
        return json_encode($val,JSON_UNESCAPED_UNICODE);
    }
    /*
     * 添加分类
     * */
    public function typesAdd($mid){
        $error = ['code'=>'1'];
        $map = [
            'mid'       => $mid,
            'storeid'   => input('sid')?input('sid'):'',
            'pic'       => input('pic')?input('pic'):'',
            'fid'       => input('fid')?input('fid'):0,
            'types'     => input('types')?input('types'):'',
            'weight'    => input('weight')?input('weight'):'',
            'addtime'   => time(),
        ];
        $result = $this->_types->save($map);
        if($result){
            return $error;
        }
        $error = ['code'=>'0','info'=>'修改失败'];
        return $error;
    }
    /*
     * 修改分类
     * */
    public function typesMod(){
        $error = ['code'=>'1'];
        $map = [
            'types'     => input('types'),
            'pic'     => input('pic'),
            'weight'    => input('weight'),
        ];
        $result = $this->_types->save($map,['id' => input('id')]);
        if($result){
            return $error;
        }
        $error = ['code'=>'0','info'=>'修改失败'];
        return $error;
    }

}