<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class VisaData extends Basely
{
    private $_visaData;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_visaData = $this;
        $this->_base = $this;
    }
    // 获取签证列表
    public function getDatas($where = [], $order = [], $page = 20){
        $join = [
            [['ww_merchant'=> 'm'], 'm.id = v.mid']
        ];
        $field = ['v.*','m.name','m.phone'];
        return $this->_visaData
            ->alias('v')
            ->join($join)
            ->field($field)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
}