<?php
namespace app\common\model;

use app\common\model\Basely;
use think\Cookie;
use think\Db;

class VisaOrder extends Basely
{
    private $_visaOrder;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_visaOrder = $this;
        $this->_base = $this;
    }
    // 获取签证订单列表
    public function getOrders($where = [], $order = [], $page = 20){
        $join = [
            [['ww_merchant'=> 'm'], 'm.id = o.mid'],
            [['ww_userinfo'=> 'u'], 'u.id = o.uid'],
            [['ly_visa'=> 'v'], 'v.id = o.vid']
        ];
        $field = ['o.*','m.name','m.phone','u.name uname','u.nickname','u.op','u.op','v.title'];
        return $this->_visaOrder
            ->alias('o')
            ->join($join)
            ->field($field)
            ->where($where)
            ->order($order)
            ->paginate($page);
    }
    // 获取操作员
    public function getOrderOps($where=[],$order=[],$page = 20){
        $orders = $this->getOrders($where,$order,$page);
        foreach ($orders as $k => $order){
            $orders[$k]['opinfo'] = Db::table('ww_userinfo')->where('id',$order['op'])->find();
        }
        return $orders;
    }
}