<?php
namespace app\admin\controller;

use app\common\controller\Common;
use think\Exception;

class Ad extends Common {

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //广告位置列表
    public function index(){
        $action = input('action');
        $action = empty($action)?'position_list':$action.'_list';
        try{
            $_ad = model('ad');
            $result = $_ad->$action();
            if(!$result){
                $this->error($_ad->getError());
            }
        }catch (Exception $e){
            return $this->error('操作错误');
        }
        $this->assign($result);
        return $this->template($action);
    }
    // 广告编辑视图
    public function edit_view(){
        $action = input('action');
        try{
            $_ad = model('ad');
            $result = $_ad->$action();
        }catch (Exception $e){
            return $this->error('操作错误');
        }
        $this->assign($result);
        return $this->template($action.'_edit');
    }
    // 广告编辑操作
    public function edit(){
        if (!$this->request->isPost()){
            return $this->error('请求出错');
        }
        $action = input('action');
        $action = $action . '_edit';
        $data = input('post.');
        try{
            $_ad = model('ad');
            $result = $_ad->$action($data);
        }catch (Exception $e){
            return $this->error('操作错误');
        }
        if($result){
            return $this->success('编辑成功','admin/Ad/index',['action'=>'position']);
        }else{
            return $this->error('编辑失败');
        }
    }

}