<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Adver extends Base{

    private $_ad;
    private $_adCategory;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_ad = model('ad');
        $this->_adCategory = model('adCategory');
    }
    //广告分类列表
    public function index(){
        $categorys = $this->_adCategory->getList();
        $page = $categorys->render();
        $this->assign([
            'title'=>'广告分类列表',
            'categorys'=>$categorys,
            'page'=>$page,
        ]);

        return $this->template();
    }
    //广告列表
    public function adver_list(){
        $cid = input('cid');
        $ad_where = ['cid'=>$cid];
        $ads = $this->_ad->getList($ad_where);
        $page = $ads->render();
        $this->assign([
            'title'=>'广告列表',
            'ads'=>$ads,
            'page'=>$page,
        ]);
        return $this->template();
    }
    // 添加广告
    public function ad_edits(){
        $act = input('act');
        $id  = input('id');
        if(empty($act)){
            $act = 'add';
        }
        if(!empty($id)){
            $act = 'update';
            $where = ['id'=>$id];
            $ad = $this->_ad->getList($where);
            if(empty($ad)){
                $this->assign('status',1);
                return $this->template();
            }
            $this->assign([
                'ad'=>$ad[0],
            ]);
        }

        $this->assign([
            'title' => '添加(修改)广告',
            'act'   => $act,
            'id'   => $id,
        ]);
        return $this->template();
    }
    // 分类操作
    public function operate(){
        $act = input('act');
        $id = input('id');
        switch ($act){
            case 'status':
                $val = input('val');

                if($val != 0){
                    $where['status'] = 1;
                }else{
                    $where['status'] = 0;
                }
                $result = $this->_ad->edit($where, ['id'=>$id]);
                break;

            case 'add':
                $where = [
                    'cid'       => input('cid')?input('cid'):'',
                    'title'     => input('title')?input('title'):'',
                    'subtitle'  => input('subtitle')?input('subtitle'):'',
                    'pic'       => input('pic')?input('pic'):'',
                    'url'       => input('url')?input('url'):'javascript:void(0);',
                    'status'    => input('status'),
                    'weight'    => input('weight'),
                    'addtime'   => time()
                ];
                if (empty($where['cid'])){
                    return $this->error('广告类目不存在');
                }
                $result = $this->_ad->edit($where);
                break;
            case 'update':
                $where = [
                    'cid'       => input('cid')?input('cid'):'',
                    'title'     => input('title')?input('title'):'',
                    'subtitle'  => input('subtitle')?input('subtitle'):'',
                    'pic'       => input('pic')?input('pic'):'',
                    'url'       => input('url')?input('url'):'javascript:void(0);',
                    'status'    => input('status'),
                    'weight'    => input('weight'),
                ];
                if (empty($where['cid'])){
                    return $this->error('广告类目不存在');
                }
                $result = $this->_ad->edit($where,['id'=>$id]);
                break;
            case 'del':
                $result = $this->_ad->typeDel(['id'=>$id]);
                break;
            default:
                return $this->error('操作失败');
                break;
        }
        if($result){
            return redirect('Adver/index');
        }else{
            return $this->error('编辑失败');
        }
    }

}