<?php
namespace app\admin\controller;

use app\common\controller;
use think\Cookie;
use think\Db;
use think\View;

class Base extends \app\common\controller\Common
{
    protected function _initialize(){
        parent::_initialize();  // TODO: Change the autogenerated stub
    }
    /**
     * 判断用户是否登录
     * */
    private function checkLogin(){
        $url = current_url();
        $where['account'] = cookie('account');
        $where['passwd'] = cookie('passwd');
        if(Cookie::get('check') == 'admin' && !empty($where['account'])){
            $this->admininfo = $this->_admin->getInfo($where);
            if(empty($this->admininfo)){
                $this->error('您操作的权限不够，请先登录！',url('Restrict/login').'?url='.$url);
            }
            cookie('account',$where['account']);
            cookie('passwd',$where['passwd']);
            cookie('check','admin');
            return true;
        }
        $this->error('您操作的权限不够，请先登录！',url('Restrict/login').'?url='.$url);
    }
    /*
     * 为模板赋必须值
     * */
    private function assigns(){
        $cache_config= getCache('basic');
        $trip_num = model('trip')->trip_num();
        $shop_num = model('shop')->shop_num();
        $user_num = model('userinfo')->user_num();
        $this->assign([
            'admininfo' => $this->admininfo,
            'cache_config' => $cache_config,
            'trip_num' => $trip_num,
            'shop_num' => $shop_num,
            'user_num' => $user_num,
        ]);
    }
}