<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Comment extends Base
{
    private $_comment;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_comment = model('comment');
    }
    // 评论列表
    public function index(){
        $this->assign([
            'title' => '评论列表',
        ]);
        return $this->template();
    }
    /*
     * 获取评论列表
     * */
    public function ask_list(){
        $this->assign([
            'title' => '产品咨询',
        ]);

        return $this->template();
    }
}