<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Config extends Base
{
    private $_config;
    private $_configKey;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_config = model('config');
        $this->_configKey = model('configKey');
    }
    // 基本配置展示
    public function basic(){
        $key = input('key')?input('key'):'basic';
        $navs = $this->_configKey->getList([],['weight'=>'desc','id'=>'asc'],0);
        $html = $this->_config->input_html($key);
        $this->assign([
            'title' => '微信参数配置',
            'html' => $html,
            'navs' => $navs,
        ]);
        return $this->template();
    }
    // 配置的编辑
    public function edits(){
        $key = input('key');
        $configs = $this->_config->edit($key);
        if($configs){
            $this->success('编辑成功');
        }
    }
}