<?php
namespace app\admin\controller;

use think\Controller;

class Dest extends Controller
{
    private $_dest;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_dest = model('dest');
    }
    /*
     * 团期分类
     * */
    public function destlist()
    {
        $dests = $this->_dest->getDestList();
        $this->assign([
            'title' => '行程分类列表',
            'dests' => $dests
        ]);
        return $this->template();
    }
}