<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Goods extends Base
{
    private $_goods;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_goods = model('goods');
    }
    /*
     * 获取商品列表
     * */
    public function goodslist(){
        $where = [];
        if(!empty($_GET['tradecode'])){
            $where['g.tradecode'] = ['like','%'.$_GET['tradecode'].'%'];
        }
        if(!empty($_GET['mid'])){
            $where['g.mid'] = $_GET['mid'];
        }
        if(!empty($_GET['name'])){
            $where['m.name'] = ['like','%'.$_GET['name'].'%'];
        }
        if(!empty($_GET['storeid'])){
            $where['g.storeid'] = $_GET['storeid'];
        }
        if(!empty($_GET['store'])){
            $where['s.store'] = ['like','%'.$_GET['store'].'%'];
        }
        if(!empty($_GET['status'])){
            $where['g.status'] = $_GET['status'];
        }
        $goodslists = $this->_goods->getGoods($where);
        $page = $goodslists->render();
        $this->assign([
            'title' => '商品列表',
            'goodslists' => $goodslists,
            'page' => $page,
        ]);

        return $this->template();
    }
}