<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Goods extends Base
{
    private $_goods;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_goods = model('goods');
    }
    // 商品分类
    public function category_list(){
        $_category = model('category');
        $categorys = $_category->getCategory();
        $view = $_category->category_view($categorys);
        $this->assign([
            'title' => '商品分类',
            'categorys' => $categorys,
            'view' => $view,
        ]);
        return $this->template();
    }
    public function ajax_category(){
        $where = ['pid'=>input('get.pid')];
        $_category = model('category');
        $categorys = $_category->getCategory($where);
        return json($categorys);

    }
    //商品分类编辑
    public function category_edit(){

        $this->assign([
            'title' => '分类编辑',
        ]);
        return $this->template();

    }
    // 分类编辑操作
    public function category(){
        if (!$this->request->isPost()){
            return $this->error('请求出错');
        }
        $data = input('post.');
        $_category = model('category');
        $result = $_category->edit($data);
        if (!$result){
            return $this->error($_category->getError());
        }
        return $this->redirect('admin/Goods/category_list');
    }
    // 品牌列表
    public function brand_list(){
        $this->assign([
            'title' => '品牌分类',
//            'goodslists' => $goodslists,
//            'page' => $page,
        ]);

        return $this->template();

    }
    // 商品列表
    public function good_list(){
        $this->assign([
            'title' => '商品列表',
        ]);

        return $this->template();

    }
    // 库存列表
    public function stock_list(){
        $this->assign([
            'title' => '商品列表',
        ]);

        return $this->template();

    }
}