<?php
namespace app\admin\controller;

use app\admin\controller\Base;
use think\Cache;
use think\Cookie;
use think\Db;

class Index extends Base
{
    private $url;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->url = current_url();
    }

    public function index()
    {

        $this->assign([
            'title' => '首页',
        ]);
        return $this->template();
    }
    public function config()
    {

        $this->assign([
            'title' => '首页',
        ]);
        return $this->template();
    }
    public function table()
    {

        $this->assign([
            'title' => '首页',
        ]);
        return $this->template();
    }
    /*
     * 清空缓存
     * */
    public function cache(){
        if(Cache::clear()){

            $this->success('清除成功，正在返回上一页面！');
        }
        $this->error('清除失败，正在返回上一页面！');

    }
}
