<?php
namespace app\admin\controller;

use think\Controller;

class Line extends Controller
{
    private $_line;
    private $_trip;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_line = model('line');
        $this->_trip = model('trip');
    }
    /*
     * 线路列表显示
     * */
    public function linelist()
    {
        $lines = $this->_line->getLineList();
        $this->assign([
            'title' => '线路列表',
            'lines' => $lines
        ]);
        return $this->template();
    }
}