<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Nav extends Base{

    private $_nav;
    private $_navCategory;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_nav = model('nav');
        $this->_navCategory = model('navCategory');
    }
    //广告分类列表
    public function index(){
        $categorys = $this->_navCategory->getList();
        $page = $categorys->render();
        $this->assign([
            'title'=>'广告分类列表',
            'categorys'=>$categorys,
            'page'=>$page,
        ]);

        return $this->template();
    }
    //广告列表
    public function nav_list(){
        $cid = input('cid');
        $nav_where = ['cid'=>$cid];
        $navs = $this->_nav->getList($nav_where);
        $page = $navs->render();
        $this->assign([
            'title'=>'广告列表',
            'navs'=>$navs,
            'page'=>$page,
        ]);
        return $this->template();
    }
    // 添加广告
    public function nav_edits(){
        $act = input('act');
        $id  = input('id');
        if(empty($act)){
            $act = 'add';
        }
        if(!empty($id)){
            $act = 'update';
            $where = ['id'=>$id];
            $nav = $this->_nav->getList($where);
            if(empty($nav)){
                $this->assign('status',1);
                return $this->template();
            }
            $this->assign([
                'nav'=>$nav[0],
            ]);
        }

        $this->assign([
            'title' => '添加(修改)广告',
            'act'   => $act,
            'id'   => $id,
        ]);
        return $this->template();
    }
    // 分类操作
    public function operate(){
        $act = input('act');
        $id = input('id');
        switch ($act){
            case 'status':
                $val = input('val');

                if($val != 0){
                    $where['status'] = 1;
                }else{
                    $where['status'] = 0;
                }
                $result = $this->_nav->edit($where, ['id'=>$id]);
                break;

            case 'add':
                $where = [
                    'cid'       => input('cid')?input('cid'):'',
                    'desc'  => input('desc')?input('desc'):'',
                    'pic'       => input('pic')?input('pic'):'',
                    'hrefstr'       => input('hrefstr')?input('hrefstr'):'javascript:void(0);',
                    'status'    => input('status'),
                    'weight'    => input('weight'),
                    'addtime'   => time()
                ];
                if (empty($where['cid'])){
                    return $this->error('导航类目不存在');
                }
                $result = $this->_nav->edit($where);
                break;
            case 'update':
                $where = [
                    'cid'       => input('cid')?input('cid'):'',
                    'desc'  => input('desc')?input('desc'):'',
                    'pic'       => input('pic')?input('pic'):'',
                    'hrefstr'       => input('hrefstr')?input('hrefstr'):'javascript:void(0);',
                    'status'    => input('status'),
                    'weight'    => input('weight'),
                ];
                if (empty($where['cid'])){
                    return $this->error('广告类目不存在');
                }
                $result = $this->_nav->edit($where,['id'=>$id]);
                break;
            case 'del':
                $result = $this->_nav->typeDel(['id'=>$id]);
                break;
            default:
                return $this->error('操作失败');
                break;
        }
        if($result){

            return redirect('Nav/index');
        }else{
            return $this->error('编辑失败');
        }
    }

}