<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Op extends Base
{
    private $_op;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_op = model('op');
    }
    public function op_list(){

    }
}