<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Orders extends Base
{
    private $_orders;
    private $_cart;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_orders = model('orders');
        $this->_cart = model('cart');
    }
    /*
     * 获取商品列表
     * */
    public function orderslist(){
        $where = [];
        if(!empty($_GET['status'])){
            $where['status'] = $_GET['status'];
        }
        if(!empty($_GET['refund'])){
            $where['refund_status'] = $_GET['refund'];
        }
        if(!empty($_GET['delivery'])){
            $where['delivery_status'] = $_GET['delivery'];
        }
        if(!empty($_GET['onumber'])){
            $where['onumber'] = ['like','%'.$_GET['onumber'].'%'];
        }
        $orderslists = $this->_orders->getList($where,['addtime'=>'desc']);
        $page = $orderslists->render();
        $this->assign([
            'title' => '订单列表',
            'orderslists' => $orderslists,
            'page' => $page,
        ]);
        return $this->template();
    }
    // 查看订单
    public function order_edit(){
        $id = input('id');
        $where = ['id'=>$id];
        $order = $this->_orders->where($where)->find();
        $error = ['code'=>1];
        if(empty($order)){
            $error['code'] = 0;
            $error['info'] = '订单不存在';
            return $this->template();
        }
        $cart_where = ['oid'=>$id];
        $goods = $this->_cart->getCarts($cart_where);
        $this->assign([
            'title' => '订单详情修改',
            'order' => $order,
            'goods' => $goods
        ]);
        return $this->template();
    }

}