<?php

namespace app\admin\controller;

use think\Controller;

class Temp extends Controller
{
    private $_temp;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_temp = model('temp');
    }
    public function templist()
    {
        $temps = $this->_temp->getTempList();
        $this->assign([
            'title' => '模板列表',
            'temps' => $temps
        ]);
        return $this->template();
    }
    public function tempedit(){

        $this->assign([
            'title' => '添加（修改）模板',
            'temps' => ''
        ]);
        return $this->template();
    }
}