<?php
namespace app\admin\controller;

class Ticket extends Base
{
    private $_ticket;
    private $_ticketOrder;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_ticket = model('ticket');
        $this->_ticketOrder = model('ticketOrder');
    }
    //门票列表
    public function piao_list(){
        $where = [];
        if(input('title')){
            $where['t.title'] = ['like', '%'.input('title').'%'];
        }
        if (input('status')){
            $where['t.status'] = input('status');
        }
        $tickets = $this->_ticket->getTickets($where);
        $page = $tickets->render($where);
        $this->assign([
            'title' => '门票列表',
            'tickets' => $tickets,
            'page' => $page
        ]);
        return $this->template();
    }
    // 门票编辑页面
    public function piao_edit(){
        $act = 'add';
        $piao = input('piao');
        if(!empty($piao)){
            $c_where = [ 'id'=>$piao, 'mid'=>$this->merchant['id'] ];
            $ticket = $this->_ticket->where($c_where)->find();

            if(!empty($ticket)){
                $act = 'update';
                $this->assign('ticket',$ticket);
            }
        }
        $this->assign([
            'title' => '门票编辑',
            'act' => $act
        ]);
        return $this->template();
    }
    public function piaoedit(){
        $act = input('act');
        $id = input('id');
        $map = [];
        $where = ['id'=>$id];
        if($act == 'adopt'){
            $map['status'] = '2';
        }
        if ($act == 'notgo'){
            $map['status'] = '0';
        }
        $result = $this->_ticket->save($map,$where);
        if($result){
            $this->success('编辑成功','Ticket/piao_list');
        }else{
            $this->error('编辑失败');
        }
    }
    //票订单
    public function piao_order(){
        $pay_status = input('pay_status');
        $uid = input('uid');
        $confirm = input('confirm');
        $where = [];
        if(!empty($pay_status)){
            $where['o.pay_status'] = $pay_status;
        }
        if(!empty($uid)){
            $where['o.uid'] = $uid;
        }
        if(!empty($confirm)){
            $where['o.confirm'] = $confirm;
        }
        $order = ['o.pay_status'=>'desc','o.addtime'=>'desc'];
        $orders = $this->_ticketOrder->getOrders($where,$order);
        $page = $orders->render($where);
        $this->assign([
            'title' => '门票订单列表',
            'orders' => $orders,
            'page' => $page
        ]);
        return $this->template();
    }
    // 看订单
    public function eye_order(){
        $oid = input('oid');
        $where = ['o.id'=>$oid];
        $orders = $this->_ticketOrder->getOrders($where,[],1);
        if(!empty($orders[0])){
            $order = $orders[0];
            $offer = json_decode($order['offer'],true);
            $this->assign([
                'order'=>$order,
                'offer' => $offer
            ]);
        }else{
            $this->error('您的订单不存在');
        }
        $this->assign([
            'title'=> '订单详情',
        ]);
        return $this->template();
    }
}