<?php
namespace app\admin\controller;

use app\admin\controller\Base;

class Types extends Base
{
    private $_malltypes;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_malltypes = model('malltypes');
    }
    //分类列表
    public function typeslist(){
        $fid = input('fid');
        $where = ['fid'=>'0'];
        if($fid){
           $where['fid'] = $fid;
        }
        $types = $this->_malltypes->getList($where);
        $page = $types->render();
        $this->assign([
            'title' => '分类列表',
            'types' => $types,
            'page'  => $page
        ]);
        return $this->template();
    }
    //分类编辑页面
    public function edits(){
        $act = input('act');
        $id  = input('id');
        if(empty($act)){
            $act = 'add';
        }
        if(!empty($id)){
            $act = 'update';
            $where = ['id'=>$id];
            $type = $this->_malltypes->getList($where);
            $this->assign([
                'type'=>$type[0],
            ]);
        }

        $this->assign([
            'title' => '店铺分类添加（修改）',
            'act'   => $act,
            'id'   => $id,
        ]);
        return $this->template();

    }
    // 分类列表的操作
    public function operate(){
        $act = input('act');
        $id = input('id');
        switch ($act){
            case 'status':
                $val = input('val');

                if($val != 0){
                    $where['status'] = 1;
                }else{
                    $where['status'] = 0;
                }
                $result = $this->_malltypes->typeEdit($where, ['id'=>$id]);
                break;
            case 'hot':
                $val = input('val');
                if($val != 0){
                    $where['is_hot'] = 1;
                }else{
                    $where['is_hot'] = 0;
                }
                $result = $this->_malltypes->typeEdit($where, ['id'=>$id]);
                break;
            case 'add':
                $where = [
                    'pic'       => input('pic')?input('pic'):'',
                    'fid'       => input('fid')?input('fid'):0,
                    'types'     => input('types'),
                    'status'    => input('status'),
                    'is_hot'    => input('is_hot'),
                    'weight'    => input('weight'),
                    'addtime'   => time(),
                ];
                $result = $this->_malltypes->typeEdit($where, []);
                break;
            case 'update':
                $where = [
                    'pic'       => input('pic'),
                    'fid'       => input('fid')?input('fid'):0,
                    'types'     => input('types'),
                    'status'    => input('status'),
                    'is_hot'    => input('is_hot'),
                    'weight'    => input('weight'),
                ];
                $result = $this->_malltypes->typeEdit($where, ['id'=>$id]);
                break;
            case 'del':
                $result = $this->_malltypes->typeDel(['id'=>$id]);
                break;
            default:
                return $this->error('操作失败');
                break;
        }
        if($result){
            return redirect('Types/typeslist');
        }else{
            return $this->error('编辑失败',url('Types/typeslist'));
        }
    }


}