<?php
namespace app\admin\controller;

use think\Db;
use think\Log;

class Visa extends Base
{
    private $_visa;
    private $_visaData;
    private $_visaOrder;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_visa = model('visa');
        $this->_visaData = model('visaData');
        $this->_visaOrder = model('visaOrder');
    }
    // 签证列表
    public function visa_list(){
        $where = [];
        if(input('title')){
            $where['v.title'] = ['like','%'.input('title').'%'];
        }
        if(input('status') == '0' || input('status')){
            $where['v.status'] = input('status');
        }
        $visas = $this->_visa->getVisas($where);
        $this->assign([
            'title' => '签证列表',
            'visas' => $visas
        ]);
        return $this->template();
    }
    // 签证编辑操作
    public function visaedit(){
        $act = input('act')?input('act'):'add';
        $visa = input('id')?input('id'):'';
        $where = ['id'=>$visa];
        switch ($act){
            case 'adopt':
                $map = ['status'=>2];
                $result = $this->_visa->save($map,$where);
                break;
            case 'notgo':
                $map = ['status'=>0];
                $result = $this->_visa->save($map,$where);
                break;
        }
        if ($result){
            return $this->success('编辑成功','Visa/visa_list');
        }else{
            return $this->error('编辑失败');
        }
    }
    // 签证所需要资料列表
    public function visa_data(){
        $where = [];
        $visa_datas = $this->_visaData->getDatas($where,[],0);
        $this->assign([
            'title' => '签证材料库',
            'visa_datas' => $visa_datas,
        ]);
        return $this->template();
    }
    // 签证资料编辑操作
    public function visa_dataedit(){
        $act = input('act');
        $data = input('data');
        $map = [
            'mid' => $this->merchant['id'],
            'title'=> input('title')?input('title'):'',
            'type'=> input('type')?input('type'):'',
            'desc'=> input('desc')?input('desc'):'',
        ];
        $case = input('case/a')?input('case/a'):[];
        $map['case'] = implode(',',$case);
        switch ($act){
            case 'add':
                $map['addtime'] = time();
                $result = $this->_visaData->save($map);
                break ;
            case 'update':
                $where = ['id'=>$data];
                $result = $this->_visaData->save($map,$where);
                break ;
        }
        if($result){
            $this->success('编辑成功','Visa/visa_data');
        }else{
            $this->error('编辑失败');
        }
    }
    // 签证订单
    public function visa_order(){
        $pay_status = input('pay_status');
        $uid = input('uid');
        $confirm = input('confirm');
        $where = [];
        if(!empty($pay_status)){
            $where['o.pay_status'] = $pay_status;
        }
        if(!empty($uid)){
            $where['o.uid'] = $uid;
        }
        if(!empty($confirm)){
            $where['o.confirm'] = $confirm;
        }
        $orders = $this->_visaOrder->getOrders($where);
        $this->assign([
            'title' => '门票订单列表',
            'orders' => $orders
        ]);
        return $this->template();
    }
    // 查看签证订单
    public function eye_order(){
        $oid = input('oid');
        $where = ['o.id'=>$oid];
        $orders = $this->_visaOrder->getOrders($where,[],1);
        if(!empty($orders[0])){
            $order = $orders[0];
            $this->assign([
                'order'=>$order,
            ]);
        }else{
            $this->error('您的订单不存在');
        }
        $this->assign([
            'title'=> '订单详情',
        ]);
        return $this->template();
    }
}