<?php
/**
 * Created by PhpStorm.
 * User: cjphp
 * Date: 2018/2/7 0007
 * Time: 11:39
 */

namespace app\common\model;


class Admin extends Base
{
//    protected $autoWriteTimestamp = true;
    protected $type = ['lastdate'=>'datetime'];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function list_where()
    {

        return parent::list_where(); // TODO: Change the autogenerated stub
    }

    public function listing()
    {
        $where = $this->list_where();
        $join = [
            ['users u',"a.uid=u.id",'left']
        ];
        $admins = $this->alias('a')->where($where)->join($join)->paginate(20);
        $admins->appends(input('get.'));

        $page = $admins->render();
        $role_groups = get_cache('roleGroup');
        $role_name = "roles.role_";
        $assigns = [
            'admins'=>$admins->toArray()['data'],
            'page'=>$page,
            'role_name'=>$role_name,
            'role_groups'=>$role_groups,
            'title'=>'管理员用户列表'
        ];
        return $assigns;
    }

    public function edit_view()
    {
        $role_groups = get_cache('roleGroup');
        $assigns = [
            'title'=>'管理员编辑',
            'role_groups'=>$role_groups,
        ];
        return $assigns;
    }

}