<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/28
 * Time: 9:24
 */

namespace app\common\model;



class Area extends Base
{
    protected $resultSetType = 'collection';
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    // 设置地区缓存
    public function setCache($pet_name=''){
        $name = lcfirst($this->name);
//        $areas = $this->select();
        $pcas = $this->pcas();
        get_cache($name,$pcas); // 配置分组缓存
    }
    public function pcas($pid = 0){
        $as = [];
        $areas = $this->where('pid',$pid)->select();
        foreach ($areas as $area){
            $as[$area['id']][] = $area['area'];
            $as[$area['id']][] = $this->pcas($area['id']);
        }
        return $as;
    }
}