<?php
namespace app\common\model;

use think\Db;
use think\Model;

class Base extends Model
{
    protected $_base;
    protected $resultSetType = 'collection';
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        Db::commit();
    }
    /*
     * 获取各列表
     * */
    public function getList($condition=[],$order=['id'=>'desc'],$page = 20){
        return $this->_base->where($condition)->order($order)->paginate($page);
    }
    // 按条件删除数据
    public function del($where = []){
        return $this->_base->where($where)->delete();

    }
    // 列表检索条件
    public function list_where(){
        $where = '';
        return $where;
    }
    // 编辑是图
    public function edit_view(){}
    // 列表获取
    public function listing(){}
    // 编辑操作
    public function edit($data){
        $this->error = '请重写方法';
        return false;
    }
    public function setCache($pet_name=''){
        //设置缓存
    }

}