<?php
namespace app\common\model;

use think\Db;

class Nav extends Base{

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    // 缓存导航
    public function setCache($pet_name=''){
        $name = lcfirst($this->name);
        $position_id = $this->db()->name('nav_position')->where('mark',$pet_name)->value('id');
        $where = ['is_show'=>1,'position'=>$position_id];
        $navs = $this->where($where)->order('weight','desc')->select()->toArray();
        get_cache($name.'.'.$pet_name,$navs);
    }
    // 获取列表
    public function listing(){
        $join = [
            ['nav_position p', 'p.id = n.position']
        ];
        $field = ['n.*','p.position'];
        $navs = $this->alias('n')->join($join)->field($field)->paginate(20);
        $page = $navs->render();
        $assign = [
            'title' => '导航列表',
            'navs' => $navs,
            'page' => $page,
        ];
        return $assign;
    }
    // 编辑视图
    public function edit_view(){
        $id = input('id');
        $assign = [];
        if(!empty($id)){
            $where = ['id'=>$id];
            $nav = $this->where($where)->find();
            $assign['nav'] = $nav;
        }
        $positions = Db::name('nav_position')->select();
        $assign['positions'] = $positions;
        $assign['title'] = '导航编辑';
        return $assign;
    }
    // 编辑操作
    public function edit($data){
        $where = [];
        if(!empty($data['id'])){
            $where['id'] = $data['id'];
        }
        $data['addtime'] = time();
        $result = $this->save($data,$where);
        $this->setCache();
        return $result;
    }
}