<?php
namespace app\admin\model;

use think\Model;
use think\Cookie;
class Admin extends Model
{
    private $_admin;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->_admin = $this;
    }
    /*
     * 验证用户登录用户名是否正确等
     * */
    public function checkAdmin($map){
        $error = ['code'=>1];
        $where = ['account'=>$map['account']];
        $exis = $this->getInfo($where);
        if($exis === false){
            $error['code'] = 0;
            $error['info'] = '用户不存在';
            return $error;
        }
        $where['passwd'] = md5($map['passwd']);
        if (strcmp($exis['passwd'],$where['passwd']) !== 0){
            $error['code'] = 0;
            $error['info'] = '账号与密码不匹配！';
            return $error;
        }
        cookie('account',$where['account']);
        cookie('passwd',$where['passwd']);
        cookie('check','admin');
        return $error;
    }
    /*
     * 根据条件获取用户信息
     * */
    public function getInfo($where=['"1"'=>'1']){
        return $this->_admin->where($where)->find();
    }

}