<?php
namespace app\index\controller;

use think\Config;

class Index extends Base
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }
    //首页
    public function index()
    {
        $categorys = get_cache('category');
        $pc_ads = get_cache('ad.pc_home');
        $home = model('category')->home();
        $this->assign([
            'title' => get_cache('config.mall')['store_title'],
            'categorys' => $categorys,
            'pc_ads' => $pc_ads,
            'home' => $home,
        ]);
        return $this->template();
    }
    public function test()
    {
        return view();
    }

    public function upload()
    {
        $file = request()->file('file');
        $o_file = $file->getInfo();
        $config = Config::get("upload");
        $info = $file->move($config['path']);
        Config::set("default_return_type", "json");
        if ($info) {
            // 成功上传后 获取上传信息
            $ret = array(
                "real_name" => $o_file["name"],
                "extension" => $info->getExtension(),
                "url" => $config["url_path"] . $info->getSaveName(),
                "saveName" => $info->getSaveName(),
                "fileName" => $info->getFilename(),
            );
            $this->success("上传成功", null, $ret);
        } else {
            // 上传失败获取错误信息
            $this->error($file->getError());
        }
    }
}

