<?php
/**
 * 支付方式选择.
 * User: Administrator
 * Date: 2017/10/13
 * Time: 17:24
 */

namespace app\index\controller;


class Payment extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}