<?php
namespace app\admin\controller;

use app\admin\controller\Base;
use think\Cache;
use think\Cookie;
use think\Db;
use think\Log;

class Index extends Base
{
    private $url;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        cache('test',1);
        $this->assign([
            'title' => '首页',
        ]);
        return $this->template();
    }
    public function config()
    {

        $this->assign([
            'title' => '首页',
        ]);
        return $this->template();
    }
    public function table()
    {

        $this->assign([
            'title' => '首页',
        ]);
        return $this->template();
    }
    /*
     * 清空缓存
     * */
    public function cache(){
        if(Cache::clear()){

            $this->success('清除成功，正在返回上一页面！');
        }
        $this->error('清除失败，正在返回上一页面！');

    }
    // 测试页面
    public function test(){
        set_time_limit(0);
        $a = strtotime(1517992261);
        dump($a);
//        ignore_user_abort(true);
//        $i = 0 ;
//        while(true && cache('test')==0){
//            Log::write($i++);
//        }
//        log::write('执行完成');
        // 用户执行关闭浏览器还会继续执行的脚本片段
    }
}
