<?php
namespace app\pc\controller;

use think\Controller;
use think\Cookie;
use think\Db;
use think\View;

class Base extends Controller
{
    protected $_userinfo;
    protected $userinfos;
    protected $theme;
    protected $controller;
    protected function _initialize(){
        parent::_initialize();  // TODO: Change the autogenerated stub
        $this->theme = 'cameo';
        $this->_userinfo = model('userinfo');
        $this->controller = $this->request->controller();

        $this->pullUserinfo();

        $this->assigns();
    }
    // 判断用户是否登录
    private function pullUserinfo(){
        $check = Cookie::get('check');

        if(strcmp($check,'user') === 0){
            $where = ['phone'=>Cookie::get('phone'),'passwd'=>Cookie::get('passwd')];
            $this->userinfos = $this->_userinfo->getUserinfo($where);
            if($this->controller == "Restrict"){
                return true;
            }
            if(empty($this->userinfos)){
                Cookie::clear();
                $this->redirect('Restrict/login');
            }
            if($this->userinfos['type'] != 3){
                $this->redirect('Restrict/store_apply');
            }
        }else{
            if($this->controller == "Restrict"){
                return true;
            }
            if(!in_array($this->action,$this->nolimit)){
                $url = current_url();
                $this->redirect(url('Restrict/login').'?url='.$url);
            }
        }
        return true;
    }
    /*
     * 为模板赋必须值
     * */
    private function assigns(){
        $cache_config= getCache('basic');
//        $trip_num = model('trip')->trip_num();
//        $shop_num = model('shop')->shop_num();
//        $user_num = model('userinfo')->user_num();
        $this->assign([
            'userinfo' => $this->userinfos,
            'cache_config' => $cache_config,
//            'trip_num' => $trip_num,
//            'shop_num' => $shop_num,
//            'user_num' => $user_num,
        ]);
    }

    /*
     * 渲染输出
     * */
    protected function template($fetch = ''){

        $temp = '';
        if($this->theme != ''){
            $temp = $this->theme .'/';
        }
        return $this->view->config('view_path',__DIR__.'/../view/'.$temp)->fetch($fetch);
    }


}