<?php
namespace app\pc\controller;
use app\pc\controller\Base;
use think\Cookie;
use think\Db;

class Index extends Base
{
    private $wechat;
    private $_ad;
    private $_nav;
    private $_offer;
    private $_line;
    private $_trip;
    private $_shop;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_ad = model('ad');
        $this->_nav = model('nav');
        $this->_offer = model('offer');
        $this->_line = model('line');
        $this->_trip = model('trip');
        $this->_shop = model('shop');
    }
    //  首页
    public function index(){
        // 消费金额
        $consume = Db::table('ww_play')->where(['type'=>2,'uid'=>$this->userinfos['id']])->sum('price');
        $this->assign('consume',-$consume);
        // 汇款汇入金额
        $import = Db::table('ww_play')->where(['type'=>1,'status'=>2,'uid'=>$this->userinfos['id']])->sum('price');
        $this->assign('import',$import);

        return $this->template();
    }
    // 表格
    public function tables(){
        return $this->template();
    }
    // 详情
    public function details(){

        return $this->template();
    }

}
