<?php
/**
 * Created by PhpStorm.
 * 订单控制器
 * User: Administrator
 * Date: 2017\10\11 0011
 * Time: 22:49
 */

namespace app\index\controller;

class Auction extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    // 立即购买，结算页面
    public function buy_now(){
        if(!$this->request->isPost()){
            return $this->error('请求错误');
        }
        $specs_group = input('post.specs_group');
        $good_id = input('post.goods_id');
        $sum = input('post.sum');
        $_good = model('goods');
        $good = $_good->buy_goods($good_id,$specs_group);
        $this->assign([
            'title' => get_cache('config.mall')['store_title'],
            'good' => $good,
            'sum' => $sum
        ]);

        return $this->template();
    }
    // 确认订单页面
    public function confirm_order(){

    }
}