<?php
/**
 * Created by PhpStorm.
 * 订单控制器
 * User: Administrator
 * Date: 2017\10\11 0011
 * Time: 22:49
 */

namespace app\index\controller;


class Auction extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    // 现在购买，结算页面
    public function buy_now(){
        
    }
}