<?php
/**
 * Created by PhpStorm.
 * 订单控制器
 * User: Administrator
 * Date: 2017\10\11 0011
 * Time: 22:49
 */

namespace app\index\controller;

class Auction extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    // 立即购买，结算页面
    public function buy_now(){
        if(!$this->request->isPost()){
            return $this->error('请求错误');
        }
        $specs_group = input('post.specs_group');
        $good_id = input('post.goods_id');
        $sum = input('post.sum');
        $_good = model('goods');
        $good = $_good->buy_goods($good_id,$specs_group);
        $this->assign([
            'title' => get_cache('config.mall')['store_title'],
            'good' => $good,
            'sum' => $sum
        ]);
        return $this->template();
    }
    // 创建订单
    public function pay_now(){
        $data = input('post.');
        $data['uid'] = $this->user['id'];
        $data['uname'] = $this->user['nickname'];
        $_orders = model('orders');
        $buy_now = $_orders->buy_now($data);
        dump($buy_now);
        $param = [
            'body' =>'', //商品主题一般为商品名
            'attach' => '', // 支付回传的值
            'trade_no' => '', // 订单号
            'fee' => '', // 价格以分为单位
            'start' => '', // 开始时间
            'expire' => '' , // 有效时间
            'goods_tag' => '', // 商品标记
            'notify_url' => '', // 回调地址
            'product_id' => '', // 商品id
        ];
    }
    // 确认订单页面
    public function confirm_order(){

    }
}