<?php
namespace app\index\controller;

use app\common\controller\Common;

class Base extends Common
{
    protected $type = 'json';
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    // 各种编辑操作
    public function edit(){
        if (!$this->request->isPost()){
            return $this->error('请求出错');
        }
        $action = input('action');
        $data = input('post.');
        try{
            $_model = model($action);
            $result = $_model->edit($data);
            if (!$result){
                return $this->error($_model->getError());
            }
            return $this->redirect('listing',['action'=>$action]);
        }catch (Exception $e){
            return $this->error('操作错误');
        }catch (ClassNotFoundException $c){
            return $this->error('操作错误');
        }
    }
}