<?php
namespace app\index\controller;

use app\common\controller\Common;

class Base extends Common
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}