<?php
namespace app\index\controller;

use think\Controller;
use think\Cookie;
use think\Url;
use think\Request;

class Base extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->action = $this->request->action();
        $this->controller = $this->request->controller();
        $this->theme = 'default';
    }
    // 渲染输出
    protected function template($fetch = ''){

        $temp = '';
        if($this->theme != ''){
            $temp = $this->theme .'/';
        }
        return $this->view->config('view_path',__DIR__.'/../view/'.$temp)->fetch($fetch);
    }
}