<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/10
 * Time: 10:25
 */

namespace app\index\controller;


class Goods extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    // 商品详情
    public function details(){
        $id = input('id');
        $where = ['goods_id' => $id];
        $_goods = model('goods');
        $good = $_goods->get_good($where);
        if(empty($good)){
            return $this->error($_goods->getError(),'index/index/index');
        }
        $assign = $good;
        $assign['title'] = $good['good']['goods_name'] . '_' . get_cache('config.mall')['store_title'];
        $this->assign($assign);
        return $this->template();
    }

}