<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/10
 * Time: 10:25
 */

namespace app\index\controller;


use think\Db;

class Goods extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }
    // 商品详情
    public function details(){
        $id = input('id');
        $where = ['goods_id' => $id];
        $_goods = model('goods');
        $good = $_goods->get_good($where);
        if(empty($good)){
            return $this->error($_goods->getError(),'index/index/index');
        }
        $assign = $good;
        $assign['title'] = $good['good']['goods_name'] . '_' . get_cache('config.mall')['store_title'];
        $this->assign($assign);
        return $this->template();
    }
    // 获取商品规格
    public function specs(){
        $goods_id = input('good_id');
        $where = ['goods_id'=>$goods_id];
        $specs = Db::name('spec_group')->where($where)->select();
        return json($specs);
    }
    // 异步验证规格组是否还存在库存
    public function ajax_spec_store(){
        $specs = input('specs/a');
        $good_id = input('goods_id');
        if(!empty($specs)){
            $specs = implode(',',$specs);
            $where = ['goods_id'=>$good_id,'specs'=>$specs];
            $spec = Db::name('spec_group')->where($where)->find();
        }else{
            $where = ['goods_id'=>$good_id];
            $good_store = Db::name('goods')->where($where)->value('store_count');
            $spec = ['store_count'=>$good_store];
        }
        return json($spec);
    }
    // 购物车页面控制器
    public function shop_cart(){

        $carts = model('cart')->where('')->select();
        $assign = [];
        $this->assign($assign);
        return $this->template();
    }

}