<?php
namespace app\index\controller;
use app\common\controller\Common;
use think\Cookie;
use think\Db;

class Index extends Common
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }
    //首页
    public function index()
    {
        $categorys = model('category')->category();

        $this->assign([
            'title' => get_cache('config.mall')['store_title'],
            'categorys' => $categorys
        ]);
        return $this->template();
    }

}

