<?php
namespace app\index\controller;
use app\common\controller\Common;

class Index extends Common
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }
    //首页
    public function index()
    {
        $categorys = get_cache('category');
        $pc_ads = get_cache('ad.pc_home');
        $navs = get_cache('nav');
        $this->assign([
            'title' => get_cache('config.mall')['store_title'],
            'categorys' => $categorys,
            'pc_ads' => $pc_ads,
            'navs' => $navs
        ]);
        return $this->template();
    }

}

