<?php
/**
 * 成员操作控制器.
 * User: Administrator
 * Date: 2017/10/12
 * Time: 15:54
 */

namespace app\index\controller;



class Member extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    // 添加地址用户地址
    public function create_addr(){
        $error = ['code'=>0,'info'=>'编辑成功'];
        if(!$this->request->isPost()){
            $error['code'] = 1;
            $error['info'] = '请求出错';
            return json($error);
        }
        $data = input('post.');
        $_address = model('address');
        $data['uid'] = $this->user['id'];
        $result = $_address->edit($data);
        if (!$result){
            $error['code'] = 1;
            $error['info'] = '编辑失败';
        }
        return json($error);
    }
}