<?php
/**
 * 成员操作控制器.
 * User: Administrator
 * Date: 2017/10/12
 * Time: 15:54
 */

namespace app\index\controller;



class Member extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    // 添加地址用户地址
    public function create_addr(){
        $error = ['code'=>0,'info'=>'编辑成功'];
        if(!$this->request->isPost()){
            $error['code'] = 1;
            $error['info'] = '请求出错';
            return json($error);
        }
        $data = input('post.');
        $_address = model('address');
        $data['uid'] = $this->user['id'];
        $result = $_address->edit($data);
        if (!$result){
            $error['code'] = 1;
            $error['info'] = '编辑失败';
        }
        return $this->type == 'json'?json($error):$error;
    }
    // 获取用户地址
    public function address(){
        $id = input('id');
        $where = ['uid'=>$this->user['id']];
        if (!empty($id)){
            $where['id']=$id;
        }
        $order = ['is_default'=>'desc'];
        $_address = model('address');
        $address = $_address->get_address($where,$order);
        return $this->type == 'json'?json($address):$address;
    }
    public function address_edit(){
        $error = ['code'=>0,'info'=>'编辑成功'];
        $data = input('post.');
        $data['uid'] = $this->user['id'];
        $_address = model('address');
        $address = $_address->modify($data);
        if (!$address){
            $error = ['code'=>1,'info'=>'编辑失败'];
        }
        return $this->type == 'json'?json($error):$error;

    }
}