<?php
namespace app\index\controller;

class Strategy extends Base
{
    private $_strategy;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_strategy = model('strategy');
    }
    // 攻略列表
    public function strategy_list(){
        $url = current_url();
        $url_info = parse_url($url);
        $where = '';
        if(!empty($url_info['query'])){
            $where = $url_info['query'];
        }
        $this->assign([
            'title' => '攻略列表',
            'where' => $where
        ]);
        return $this->template();
    }
    //异步获取攻略列表信息
    public function ajax_strategy(){
        $where = $this->_strategy->getWhere();
        $strategys = $this->_strategy->getStrategys($where);
        $this->assign('strategys',$strategys);
        return $this->template();
    }
    // 门票详情
    public function details(){
        $strategy = $this->_strategy->getStrategy();
        if(empty($strategy)){
            $this->error('攻略不存在',url('Index/index'));
        }
        $this->assign([
            'title' => !empty($strategy['title'])?$strategy['title']:'小惠猫-旅游攻略',
            'strategy' => $strategy,
        ]);
        return $this->template();
    }
}