<?php
namespace app\api\controller;
use think\Cache;
use think\Controller;
use think\Session;

class Webase extends Controller
{
    protected $wConfig; // 微信配置内容
    protected $_config; // 配置模型
    protected $wechat;  // 微信接口集成
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->init();
    }
    //初始化类
    private function init(){
        Vendor('Wechat.Wechat','.class.php');
        $this->_config = model('config');
        $this->wConfig = getCache('wechat');
        $this->wechat  =  new \Wechat($this->wConfig['appid'],$this->wConfig['appsecret'],$this->wConfig['access_token']);
        $this->access_token(); // 获取微信access_token
    }

    //获取微信access_token
    public function access_token(){
        $apis = $this->wConfig;
        $access = [];
        if($apis['expires_in'] < time()){ //过期
            $access = $this->wechat->cgi_access();
            $access['expires_in'] = time()+7100;
            $this->wConfig = array_merge($this->wConfig,$access);
            $this->wechat  =  new \Wechat($this->wConfig['appid'],$this->wConfig['appsecret'],$this->wConfig['access_token']);
            $this->_config->onedit($access);
        }
        return $access;
    }
    public function GetOpenid($url='',$scope=true,$state='' ,&$userinfo = []){
        $wx_openid = Session::get('wx_openid');
//        dump($wx_openid);exit;
        if(empty($wx_openid))
        {
            if(empty($_GET['code'])){
                return $this->redirect($this->wechat->oauth2_authorize($url,$scope,$state));
            }
            $access = $this->wechat->oauth2_access();
            if(!empty($access['errcode']) && $access['errcode'] == 40163){
                return $this->redirect($this->wechat->oauth2_authorize($url,$scope,$state));
            }
            if(empty($access['openid'])){
                return $this->redirect($this->wechat->oauth2_authorize($url,$scope,$state));
            }
            $userinfo = $this->wechat->oauth2_userinfo($access['access_token'],$access['openid']);
            $wx_openid = $access['openid'];
            Session::set('wx_openid',$wx_openid);
        }
        return $wx_openid;
    }
}