<?php
namespace app\merchant\controller;

use app\merchant\controller\Base;

class Comment extends Base
{
    private $_comment;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_comment = model('comment');
    }
    /*
     * 获取评论列表
     * */
    public function commentlist(){
        $where = ['c.mid'=>$this->merchant['id']];
        $orderlist = ['addtime'=>'desc'];
        $comments = $this->_comment->getComments($where,$orderlist);

        $page = $comments->render();
        $this->assign([
            'title' => '商品列表',
            'comments' => $comments,
            'page' => $page,
        ]);
        return $this->template();
    }
}