<?php
namespace app\merchant\controller;

use app\merchant\controller\Base;

class Goods extends Base
{
    private $_goods;
    private $_malltypes ;
    private $_types ;
    private $_store ;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_goods = model('goods');
        $this->_malltypes = model('malltypes');
        $this->_types = model('types');
        $this->_store = model('store');
    }
    /*
     * 获取商品列表
     * */
    public function goodslist(){
        $where = ['g.mid'=>$this->merchant['id']];
        if(input('tradename')){
            $where['g.tradename'] = ['like','%'.input('tradename').'%'];
        }
        if(input('id')){
            $where['g.id'] = input('id');
        }
        $order = ['g.weight'=>'desc','g.addtime'=>'desc'];
        $goodslists = $this->_goods->getGoods($where,$order);
        $page = $goodslists->render();
        $this->assign([
            'title' => '商品列表',
            'goodslists' => $goodslists,
            'page' => $page,
        ]);

        return $this->template();
    }
    /*
     * 商品的添加修改
     * */
    public function goodsedit(){
        $act = input('act');
        $gid = input('gid');

        if(!empty($act)){
            $errors = ['code'=>1];
            if(strcmp($act,'add') === 0){
                $result = $this->_goods->goodsAdd($this->merchant['id']);
                if($result['code'] == 0){
                    $this->error($result['info']);
                }
                $errors['info'] = '添加成功';
                $this->success($errors['info'],url('Goods/goodslist'));
            }elseif(strcmp($act,'update') === 0){
                $result = $this->_goods->goodsMod($this->merchant['id'],$gid);
                if($result['code'] == 0){
                    $this->error($result['info']);
                }
                $errors['info'] = '修改成功';
                $this->success($errors['info'],url('Goods/goodslist'));
            }else{
                $this->error('操作错误！');
            }
        }else{
            $act = 'add';
        }
        if(!empty($gid)){
            $act = 'update';
            $where = ['id'=>$gid];
            $goods = $this->_goods->getList($where);
//            $specs = $this->_specs->callSpecs(['gid'=>$gid]);
            $this->assign([
                'goods'=>$goods[0],
            ]);
        }
        $malltypes = $this->_malltypes->getList(['fid'=>0],['weight'=>'desc','id'=>'asc']);
        $stores = $this->_store->getStores($this->merchant['id']);

        $this->assign([
            'title' => '商品添加',
            'act'   => $act,
            'gid'   => $gid,
            'malltypes' => $malltypes,
            'stores' => $stores,
        ]);
        return $this->template();
    }
    //修改商品上架状态
    public function edit(){
        $act = input('act');
        $id = input('id');
        $where = ['id'=>$id];
        if($act == 'grounding'){
            $map = ['status'=>input('status')];
        }
        dump($map);
        if($this->_goods->save($map,$where))
        {
            $this->success('修改成功');
        }else{
            $this->success('修改失败');
        }
    }
    public function good_del(){
        $id = input('id');
        $where = ['id'=>$id];
        $result = $this->_goods->where($where)->delete();
        if($result){
            $this->success('删除成功！');
        }else{
            $this->error('删除失败');
        }
    }
}