<?php
namespace app\restrict\controller;

use app\common\controller\Common;
use think\Db;
use think\Exception;

class Index extends Common {
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 用户登录模板
     */
    public function index(){
        $url = input('url');
        $this->assign([
            'url' => $url,
            'title' => '登录'
            ]);
        return $this->template();
    }
    /**
     * 用户注册模板
     */
    public function register(){
        $this->assign('title','注册新用户');
        return $this->template();
    }
    /**
     * 验证码验证
     * @return string
     **/
    public function checkcode(){
        $data = [];
        $code = input('code') ?: '';
        $error = ['code'=>0];
        $data['captcha'] = $code;
        $result = $this->validate($data,[
            'captcha|验证码'=>'require|captcha'
        ]);
        if($result !== true){
            $error['info'] = $result;
        }else{
            $error['code'] = $result;
        }
        return json_encode($error,JSON_UNESCAPED_UNICODE);
    }
    /**
     * 创建用户
     */
    public function create(){
        if(!$this->request->isPost()){
            return $this->error('请求出错');
        }
        $data = input('post.');
        $_users = model('users');
        $data['regip'] = $this->request->ip();
        $data['domain'] = $this->request->domain();
        $result = $_users->register($data);
        if($result['code']===0){
            $user = Db::name('users')->where($data['reg_type'],$data['$data["reg_type"]'])->find();
            $this->record_user($user);
            return $this->success($result['info'],
                url('index/Index/index'));
        }
        return $this->error($result['info']);
    }
    /**
     * 邮箱验证
     */
    public function mailprove(){
        $checkcode= input('get.checkcode');
        $key = get_cache('config.basic')['encrypt_key'];
        $decode = authcode($checkcode,$key,'D');
        if (!$decode){
            dump('验证错误');
        }
        $result = explode('!_!',$decode);
        $user = Db::name('users')->where('email',$result[0])->find();
        if(empty($user)){
            return $this->error('该邮箱未注册',
                url('restrict/Index/register'));
        }
        if(strcmp($user['passwd'],$result[1]) === 0){
            $up = Db::name('users')
                ->where('id',$user['id'])
                ->update(['mail_verify'=>1]);
            if(!$up){
                return $this->error('系统出错');
            }
            $this->record_user($user);
            return $this->success('验证成功',
                url('index/Index/index'));
        }else{
            return $this->error('验证失败,请登录后重新发送验证！',
                url('restrict/Index/register'));
        }
    }
    /**
     * 测试功能
     */
    public function test(){
        $send = [
            'to'=>'1767158841@qq.com',
            'subject' => '测试邮件',
            'body' => '邮件内容很隐秘哦',
            'name' => '' // 称呼
        ];
        $to = '1767158841@qq.com';
        $subject = '测试邮件';
        $body = '邮件内容很隐秘哦';
        $name = '';
        $result = send_mail($to,$name,$subject,$body);
        dump($result);
    }
}