<?php
namespace app\common\controller;

use think\Controller;
use think\Cookie;
use think\Db;


class Common extends Controller
{
    protected $theme; // 主题控制
    protected $module; //当前请求模块
    protected $controller; //当前请求控制器
    protected $action; //当前请求方法
    protected $user; //当前请求方法
    protected function _initialize(){
        parent::_initialize();  // TODO: Change the autogenerated stub
        $this->theme = 'appui';
        $this->module = $this->request->module(); // 获取模块
        $this->controller = $this->request->controller(); // 获取控制器
        $this->action = $this->request->action(); // 获取方法
    }
    /**
     * 判断用户是否登录
     */
    private function checkLogin(){
        $cookie_id = Cookie::get('token');
        $cookie_secret = Cookie::get('secret');
        $_user = model('users');
        $this->user = $_user->checkLogin($cookie_id,$cookie_secret);
        $_auth = model('auth');



    }
    /**
     * 用户信息储存
     * @param mixed $user 用户信息
     * @return  null
     */
    protected function record_user(){
        $key = get_cache('config.basic')['encrypt_key'];
        if(!$this->user){
            return false;
        }
        $id = authcode($this->user['id'],$key);
        $secret = authcode($this->user['passwd'],$key);
        Cookie::set('token',$id);
        Cookie::set('secret',$secret);
    }

    /**
     * 设置用户信息
     */
    public function setUser($user){
        $this->user = $user;
    }
    /**
     * 渲染输出
     * @param string $fetch 显示模板
     */
    protected function template($fetch = ''){

        $temp = '';
        if($this->theme != ''){
            $temp .= $this->theme .'/';
        }
        if(!empty($this->module)){
            $temp .= $this->module .'/';
        }
        return $this->view->config('view_path',__DIR__.'/../view/'.$temp)->fetch($fetch);
    }
    /**
     * 获取跳转到当前页的地址
     */
    protected function last_url(){
        return $_SERVER["HTTP_REFERER"] ?:url('index/Index/index');
    }
    /**
     * 跳转到上一页
     */
    protected function last_redirect(){
        return $this->redirect($this->last_url());
    }



}